# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the bin/rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
puts "Seeding data"

first_user = User.create(name: "James Smith", email_address: "jimbo88@gmail.com", password: "123")
second_user = User.create(name: "Jennifer Smith", email_address: "jennysmith@gmail.com", password: "123")
third_user = User.create(name: "Richard Clifton", email_address: "rich1955@yahoo.com", password: "123")
fourth_user = User.create(name: "Maria Essex", email_address: "mariaanna77@aol.com", password: "123")

first_account = Account.create(name: "checking")
second_account = Account.create(name: "checking")
third_account = Account.create(name: "checking")
fourth_account = Account.create(name: "savings")
fifth_account = Account.create(name: "savings")
sixth_account = Account.create(name: "savings")

first_client = Client.create(user: first_user, account: first_account)
second_client = Client.create(user: second_user, account: first_account)
third_client = Client.create(user: third_user, account: second_account)
fourth_client = Client.create(user: fourth_user, account: third_account)
fifth_client = Client.create(user: first_user, account: fourth_account)
sixth_client = Client.create(user: second_user, account: fourth_account)
seventh_client = Client.create(user: third_user, account: fifth_account)
eighth_client = Client.create(user: fourth_user, account: sixth_account)

transaction_1 = Transaction.create(account: first_account, date: "August 1st", description: "Target", dollar_amount: -103.59 ) 
transaction_2 = Transaction.create(account: first_account, date: "August 5th", description: "Northwest School District Payroll", dollar_amount: 1575)
transaction_3 = Transaction.create(account: first_account, date: "August 6th", description: "Chipotle", dollar_amount: -18.50)
transaction_4 = Transaction.create(account: first_account, date: "August 10th", description: "Trader Joes", dollar_amount: -79.98)
transaction_5 = Transaction.create(account: first_account, date: "August 11th", description: "Amazon", dollar_amount: -55.60 )
transaction_6 = Transaction.create(account: first_account, date: "August 12th", description: "Gap", dollar_amount: -45 )
transaction_7 = Transaction.create(account: first_account, date: "August 13th", description: "McDonalds", dollar_amount: -20)
transaction_8 = Transaction.create(account: first_account, date: "August 14th", description: "PSEG", dollar_amount: -110)
transaction_9 = Transaction.create(account: first_account, date: "August 15th", description: "Northwest School District Payroll", dollar_amount: 1575)
transaction_10 = Transaction.create(account: first_account, date: "August 18th", description: "Home Depot", dollar_amount: -88.50)
transaction_11 = Transaction.create(account: second_account, date: "July 28th", description: "Home Depot", dollar_amount: -45.23) 
transaction_12 = Transaction.create(account: second_account, date: "August 1st", description: "Social Security Deposit", dollar_amount: 1300)
transaction_13 = Transaction.create(account: second_account, date: "August 2nd", description: "Walmart", dollar_amount: -34.80)
transaction_14 = Transaction.create(account: second_account, date: "August 7th", description: "Transfer To Savings Account", dollar_amount: -500)
transaction_15 = Transaction.create(account: second_account, date: "August 10th", description: "Netflix", dollar_amount: -15.50)
transaction_16 = Transaction.create(account: second_account, date: "August 10th", description: "CVS", dollar_amount: -80)
transaction_17 = Transaction.create(account: second_account, date: "August 11th", description: "ShopRite", dollar_amount: -76.55)
transaction_18 = Transaction.create(account: second_account, date: "August 15th", description: "Auto Zone", dollar_amount: -23.57)
transaction_19 = Transaction.create(account: second_account, date: "August 17th", description: "Wawa", dollar_amount: -35.90)
transaction_20 = Transaction.create(account: second_account, date: "August 19th", description: "LL Bean", dollar_amount: -125.00)
transaction_21 = Transaction.create(account: third_account, date: "July 29th", description: "Disney Plus", dollar_amount: -25)
transaction_22 = Transaction.create(account: third_account, date: "August 1st", description: "JP Morgan Payroll", dollar_amount: 2250.00)
transaction_23 = Transaction.create(account: third_account, date: "August 3rd", description: "CVS - ATM", dollar_amount: -25.00)
transaction_24 = Transaction.create(account: third_account, date: "August 3rd", description: "ShopRite", dollar_amount: -145.75)
transaction_25 = Transaction.create(account: third_account, date: "August 8th", description: "Trader Joes", dollar_amount: -45.57)
transaction_26 = Transaction.create(account: third_account, date: "August 19th", description: "Shoe Factory", dollar_amount: -85.60)
transaction_27 = Transaction.create(account: third_account, date: "August 22nd", description: "Kandi Apple Sweete Shoppe", dollar_amount: -25.50)
transaction_28 = Transaction.create(account: third_account, date: "August 23rd", description: "CVS - ATM", dollar_amount: -65.00)
transaction_29 = Transaction.create(account: third_account, date: "August 24th", description: "Target", dollar_amount: -57.77)
transaction_30 = Transaction.create(account: third_account, date: "August 25th", description: "AMC", dollar_amount: -35.00)
transaction_31 = Transaction.create(account: fourth_account, date: "August 3rd", description: "ATM - Main Street Wawa", dollar_amount: -20.00)
transaction_32 = Transaction.create(account: fourth_account, date: "August 12", description: "Cash Deposit", dollar_amount: 400.00)
transaction_33 = Transaction.create(account: fourth_account, date: "August 17th", description: "ATM - Main Street Wawa", dollar_amount: -40.00)
transaction_34 = Transaction.create(account: fourth_account, date: "August 25th", description: "ATM - Target", dollar_amount: -35.00)
transaction_35 = Transaction.create(account: fourth_account, date: "August 27th", description: "ATM - Target", dollar_amount: -65.00)
transaction_36 = Transaction.create(account: fifth_account, date: "August 7th", description: "Transfer From Checking Account", dollar_amount: 500)
transaction_37 = Transaction.create(account: fifth_account, date: "August 10th", description: "Stock Dividends", dollar_amount: 670.50)
transaction_38 = Transaction.create(account: fifth_account, date: "August 15th", description: "ATM - CVS", dollar_amount: -85.00)
transaction_39 = Transaction.create(account: fifth_account, date: "August 27th", description: "Branch Withdrawal", dollar_amount: -100.00)
transaction_40 = Transaction.create(account: fifth_account, date: "August 29th", description: "ATM - CVS", dollar_amount: -25.00)
transaction_41 = Transaction.create(account: sixth_account, date: "August 1st", description: "Transfer to Wells Fargo", dollar_amount: -250.00)
transaction_42 = Transaction.create(account: sixth_account, date: "August 3rd", description: "Transfer to Wells Fargo", dollar_amount: -500.00)
transaction_43 = Transaction.create(account: sixth_account, date: "August 10th", description: "Transfer to Wells Fargo", dollar_amount: -275.00)
transaction_44 = Transaction.create(account: sixth_account, date: "August 15th", description: "Transfer to Wells Fargo", dollar_amount: -100.00)
transaction_45 = Transaction.create(account: sixth_account, date: "August 20th", description: "Transfer to Wells Fargo", dollar_amount: -250.00)


puts "Done seeding"